version: '2'
services:
  lint-test:
    build:
      context: .
      dockerfile: Dockerfile-lint-test
    command:
      - bash
      - '-c'
      - 'rustfmt --write-mode=diff
           src/**.rs 
         && cargo clippy --all
         && cargo test --all'
